[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.31.1"

[programs.devnet]
samachi_staking = "8n1omncNHsRzUARf4w5jAqXjLJihiCCgESixrzj7EJSJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "cargo build-sbf"
